steps:
  # 1. Install dependencies at repo root
  - id: "npm ci"
    name: "gcr.io/cloud-builders/npm"
    args: ["ci"]

  # 2. Build the add-in (Webpack -> dist/)
  - id: "build add-in"
    name: "gcr.io/cloud-builders/npm"
    args: ["run, "build"]
    env:
      # optional; only if you actually use process.env.APP_ENV
      - "APP_ENV=${_ENVIRONMENT}"

  # 3. Upload built web assets (everything under dist/) to env-specific bucket
  - id: "upload web assets"
    name: "gcr.io/cloud-builders/gsutil"
    dir: "dist"
    args:
      [
        "-m",
        "rsync",
        "-r",
        "-c",
        "-d",
        ".",
        "gs://mainsequence-excel-addin-${_ENVIRONMENT}/web"
      ]

  # 4. Pick the right manifest based on environment and upload it
  - id: "upload manifest"
    name: "gcr.io/cloud-builders/gcloud"
    dir: "."
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "ENVIRONMENT=${_ENVIRONMENT}"
        if [ "${_ENVIRONMENT}" = "development" ]; then
          echo "Using manifest.dev.xml"
          gsutil cp manifest.dev.xml "gs://mainsequence-excel-addin-${_ENVIRONMENT}/manifest.xml"
        else
          echo "Using manifest.xml"
          gsutil cp manifest.xml "gs://mainsequence-excel-addin-${_ENVIRONMENT}/manifest.xml"
        fi

substitutions:
  _ENVIRONMENT: $_TF_ENVIRONMENT

options:
  logging: CLOUD_LOGGING_ONLY
